name: generator_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.0 <3.0.0'
dependencies: 
  build: ^2.0.3
  source_gen: 1.0.5
  path: ^1.8.2
  build_runner: ^2.2.1
  code_builder: ^4.1.0
  dart_style: ^2.0.2
  recase: ^4.0.0
  auto_route_generator: 
    path: /Users/ericm/sunny/local_plugins/auto_route_library/auto_route_generator
  auto_route: 
    path: /Users/ericm/sunny/local_plugins/auto_route_library/auto_route
dev_dependencies: 
  build_test: ^2.1.2
  test: ^1.17.9
dependency_overrides: 
  meta: ^1.8.0
flutter: 
  uses-material-design: true
