name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  provider: ^6.0.5
  url_strategy: ^0.2.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  auto_route: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/auto_route_library/auto_route
dev_dependencies: 
  build_runner: ^2.4.0
  effective_dart: ^1.3.2
  flutter_test: 
    sdk: flutter
  auto_route_generator: 
    path: /Users/ericm/reliveit/checkout/ericmartineau/auto_route_library/auto_route_generator
flutter: 
  uses-material-design: true
